// src/systems/ExpandedReactions.ts
// Reações químicas adicionais - 35+ novas reações
import type { ChemicalReaction, Substance } from './ChemistryEngine'

// ═══════════════════════════════════════════════════════════════════════
// NOVAS SUBSTÂNCIAS
// ═══════════════════════════════════════════════════════════════════════
export const EXPANDED_SUBSTANCES: Record<string, Substance> = {
    // ÁCIDOS ADICIONAIS
    'H2CO3': { formula: 'H2CO3', name: 'Ácido Carbônico', molarMass: 62.03, color: '#f8f8ff', phase: 'aqueous', ph: 4.2, category: 'acid' },
    'HBr': { formula: 'HBr', name: 'Ácido Bromídrico', molarMass: 80.91, color: '#ffe4c4', phase: 'aqueous', ph: 0.9, category: 'acid' },
    'HI': { formula: 'HI', name: 'Ácido Iodídrico', molarMass: 127.91, color: '#fff0f5', phase: 'aqueous', ph: 0.8, category: 'acid' },
    'H2S': { formula: 'H2S', name: 'Ácido Sulfídrico', molarMass: 34.08, color: '#fffacd', phase: 'gas', category: 'acid', isToxic: true },
    'HClO': { formula: 'HClO', name: 'Ácido Hipocloroso', molarMass: 52.46, color: '#e0ffff', phase: 'aqueous', ph: 4.5, category: 'acid' },
    'H2C2O4': { formula: 'H2C2O4', name: 'Ácido Oxálico', molarMass: 90.03, color: '#ffffff', phase: 'solid', ph: 1.3, category: 'acid' },

    // BASES ADICIONAIS
    'Ba(OH)2': { formula: 'Ba(OH)2', name: 'Hidróxido de Bário', molarMass: 171.34, color: '#f0fff0', phase: 'aqueous', ph: 13.5, category: 'base' },
    'Al(OH)3': { formula: 'Al(OH)3', name: 'Hidróxido de Alumínio', molarMass: 78.0, color: '#ffffff', phase: 'solid', ph: 9, category: 'base' },
    'Fe(OH)2': { formula: 'Fe(OH)2', name: 'Hidróxido de Ferro II', molarMass: 89.86, color: '#90ee90', phase: 'solid', ph: 9, category: 'base' },
    'Fe(OH)3': { formula: 'Fe(OH)3', name: 'Hidróxido de Ferro III', molarMass: 106.87, color: '#8b4513', phase: 'solid', ph: 7, category: 'base' },
    'Zn(OH)2': { formula: 'Zn(OH)2', name: 'Hidróxido de Zinco', molarMass: 99.42, color: '#ffffff', phase: 'solid', ph: 9, category: 'base' },

    // SAIS ADICIONAIS
    'MgSO4': { formula: 'MgSO4', name: 'Sulfato de Magnésio', molarMass: 120.37, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },
    'CaCl2': { formula: 'CaCl2', name: 'Cloreto de Cálcio', molarMass: 110.98, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },
    'KMnO4': { formula: 'KMnO4', name: 'Permanganato de Potássio', molarMass: 158.03, color: '#800080', phase: 'solid', ph: 7, category: 'salt' },
    'K2Cr2O7': { formula: 'K2Cr2O7', name: 'Dicromato de Potássio', molarMass: 294.19, color: '#ff4500', phase: 'solid', ph: 4, category: 'salt' },
    'Na2S2O3': { formula: 'Na2S2O3', name: 'Tiossulfato de Sódio', molarMass: 158.11, color: '#ffffff', phase: 'solid', ph: 8, category: 'salt' },
    'FeSO4': { formula: 'FeSO4', name: 'Sulfato de Ferro II', molarMass: 151.91, color: '#90ee90', phase: 'solid', ph: 4, category: 'salt' },
    'ZnSO4': { formula: 'ZnSO4', name: 'Sulfato de Zinco', molarMass: 161.47, color: '#ffffff', phase: 'aqueous', ph: 5, category: 'salt' },
    'CuCl2': { formula: 'CuCl2', name: 'Cloreto de Cobre II', molarMass: 134.45, color: '#00ced1', phase: 'aqueous', ph: 4, category: 'salt' },
    'NaBr': { formula: 'NaBr', name: 'Brometo de Sódio', molarMass: 102.89, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },
    'NaI': { formula: 'NaI', name: 'Iodeto de Sódio', molarMass: 149.89, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },
    'AgBr': { formula: 'AgBr', name: 'Brometo de Prata', molarMass: 187.77, color: '#fffacd', phase: 'solid', ph: 7, category: 'salt' },
    'AgI': { formula: 'AgI', name: 'Iodeto de Prata', molarMass: 234.77, color: '#ffff00', phase: 'solid', ph: 7, category: 'salt' },
    'PbCl2': { formula: 'PbCl2', name: 'Cloreto de Chumbo II', molarMass: 278.1, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt', isToxic: true },
    'PbI2': { formula: 'PbI2', name: 'Iodeto de Chumbo II', molarMass: 461.01, color: '#ffd700', phase: 'solid', ph: 7, category: 'salt', isToxic: true },
    'BaSO4': { formula: 'BaSO4', name: 'Sulfato de Bário', molarMass: 233.39, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },
    'KSCN': { formula: 'KSCN', name: 'Tiocianato de Potássio', molarMass: 97.18, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },
    'Na2SO4': { formula: 'Na2SO4', name: 'Sulfato de Sódio', molarMass: 142.04, color: '#ffffff', phase: 'solid', ph: 7, category: 'salt' },

    // GASES ADICIONAIS
    'NO2': { formula: 'NO2', name: 'Dióxido de Nitrogênio', molarMass: 46.01, color: '#8b4513', phase: 'gas', category: 'gas', isToxic: true },
    'NO': { formula: 'NO', name: 'Óxido Nítrico', molarMass: 30.01, color: '#e8e8e8', phase: 'gas', category: 'gas', isToxic: true },
    'CO': { formula: 'CO', name: 'Monóxido de Carbono', molarMass: 28.01, color: '#e8e8e8', phase: 'gas', category: 'gas', isToxic: true },
    'MnO2': { formula: 'MnO2', name: 'Dióxido de Manganês', molarMass: 86.94, color: '#2f2f2f', phase: 'solid', category: 'salt' },
    'I2': { formula: 'I2', name: 'Iodo', molarMass: 253.81, color: '#4b0082', phase: 'solid', category: 'gas' },
    'Br2': { formula: 'Br2', name: 'Bromo', molarMass: 159.81, color: '#8b0000', phase: 'liquid', category: 'gas', isToxic: true },

    // OXIDANTES/REDUTORES
    'H2O2': { formula: 'H2O2', name: 'Peróxido de Hidrogênio', molarMass: 34.01, color: '#f0ffff', phase: 'liquid', ph: 4.5, category: 'acid' },
    'Na2O2': { formula: 'Na2O2', name: 'Peróxido de Sódio', molarMass: 77.98, color: '#fffacd', phase: 'solid', category: 'salt' },

    // INDICADORES ADICIONAIS
    'bromothymol': { formula: 'C27H28Br2O5S', name: 'Azul de Bromotimol', molarMass: 624.38, color: '#00ff00', phase: 'liquid', category: 'indicator' },
    'universal': { formula: 'universal', name: 'Indicador Universal', molarMass: 0, color: '#90ee90', phase: 'liquid', category: 'indicator' },

    // ORGÂNICOS ADICIONAIS  
    'CH3CHO': { formula: 'CH3CHO', name: 'Acetaldeído', molarMass: 44.05, color: '#fffacd', phase: 'liquid', category: 'organic', isFlammable: true },
    'HCHO': { formula: 'HCHO', name: 'Formaldeído', molarMass: 30.03, color: '#f5f5f5', phase: 'gas', category: 'organic', isToxic: true },
    'CH3COCH3': { formula: 'CH3COCH3', name: 'Acetona', molarMass: 58.08, color: '#f8f8ff', phase: 'liquid', category: 'organic', isFlammable: true },
    'C6H6': { formula: 'C6H6', name: 'Benzeno', molarMass: 78.11, color: '#fffacd', phase: 'liquid', category: 'organic', isFlammable: true, isToxic: true },
    'C3H8O3': { formula: 'C3H8O3', name: 'Glicerina', molarMass: 92.09, color: '#f0f8ff', phase: 'liquid', category: 'organic' },
    'C6H10O5': { formula: 'C6H10O5', name: 'Amido', molarMass: 162.14, color: '#ffffff', phase: 'solid', category: 'organic' },
    'C': { formula: 'C', name: 'Carbono', molarMass: 12.01, color: '#333333', phase: 'solid', category: 'organic', isFlammable: true },
    'CH4': { formula: 'CH4', name: 'Metano', molarMass: 16.04, color: '#f5f5f5', phase: 'gas', category: 'gas', isFlammable: true },
}


// ═══════════════════════════════════════════════════════════════════════
// NOVAS REAÇÕES QUÍMICAS (35+)
// ═══════════════════════════════════════════════════════════════════════
export const EXPANDED_REACTIONS: ChemicalReaction[] = [
    // ═══════════════════════════════════════════════════════════════════
    // REAÇÕES REDOX (Oxidação-Redução)
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'kmno4-feso4',
        reactants: ['KMnO4', 'FeSO4'],
        products: ['MnSO4', 'Fe2(SO4)3', 'K2SO4'],
        equation: '2KMnO₄ + 10FeSO₄ + 8H₂SO₄ → 2MnSO₄ + 5Fe₂(SO₄)₃ + K₂SO₄ + 8H₂O',
        description: 'REDOX: Permanganato oxida ferro II a ferro III!',
        type: 'displacement',
        effect: 'glow',
        effectColor: '#90ee90',
        productColor: '#ffa500',
        exothermic: true,
    },
    {
        id: 'kmno4-h2o2',
        reactants: ['KMnO4', 'H2O2'],
        products: ['MnO2', 'O2', 'KOH'],
        equation: '2KMnO₄ + 3H₂O₂ → 2MnO₂ + 3O₂↑ + 2KOH + 2H₂O',
        description: 'REDOX violenta! Liberação de oxigênio com efervescência!',
        type: 'decomposition',
        effect: 'bubbles',
        effectColor: '#ffffff',
        productColor: '#8b4513',
        exothermic: true,
        requiredTemp: { min: 0, max: 80 },
    },
    {
        id: 'k2cr2o7-c2h5oh',
        reactants: ['K2Cr2O7', 'C2H5OH'],
        products: ['Cr2(SO4)3', 'CH3CHO', 'K2SO4'],
        equation: 'K₂Cr₂O₇ + 3C₂H₅OH + 4H₂SO₄ → Cr₂(SO₄)₃ + 3CH₃CHO + K₂SO₄ + 7H₂O',
        description: 'Bafômetro! Dicromato oxida etanol (laranja → verde)',
        type: 'displacement',
        effect: 'glow',
        effectColor: '#228b22',
        productColor: '#228b22',
        exothermic: true,
    },
    {
        id: 'zn-cuso4',
        reactants: ['Zn', 'CuSO4'],
        products: ['ZnSO4', 'Cu'],
        equation: 'Zn + CuSO₄ → ZnSO₄ + Cu',
        description: 'Deslocamento: Zinco desloca cobre (deposição de cobre metálico)',
        type: 'displacement',
        effect: 'precipitate',
        effectColor: '#b87333',
        productColor: '#f5f5f5',
        exothermic: true,
    },
    {
        id: 'mg-o2',
        reactants: ['Mg', 'O2'],
        products: ['MgO'],
        equation: '2Mg + O₂ → 2MgO',
        description: 'COMBUSTÃO BRILHANTE! Magnésio queimando (luz intensa)',
        type: 'combustion',
        effect: 'fire',
        effectColor: '#ffffff',
        productColor: '#f5f5f5',
        exothermic: true,
        requiredTemp: { min: 450, max: 5000 },
    },
    {
        id: 'fe-o2',
        reactants: ['Fe', 'O2'],
        products: ['Fe2O3'],
        equation: '4Fe + 3O₂ → 2Fe₂O₃',
        description: 'Oxidação do ferro: Formação de ferrugem',
        type: 'synthesis',
        effect: 'glow',
        effectColor: '#8b4513',
        productColor: '#a0522d',
        exothermic: true,
        requiredTemp: { min: 100, max: 5000 },
    },
    {
        id: 'cu-hno3',
        reactants: ['Cu', 'HNO3'],
        products: ['Cu(NO3)2', 'NO2', 'H2O'],
        equation: 'Cu + 4HNO₃(conc) → Cu(NO₃)₂ + 2NO₂↑ + 2H₂O',
        description: 'Cobre + ácido nítrico: Fumos castanhos de NO₂!',
        type: 'displacement',
        effect: 'smoke',
        effectColor: '#8b4513',
        productColor: '#4169e1',
        exothermic: true,
    },

    // ═══════════════════════════════════════════════════════════════════
    // REAÇÕES DE PRECIPITAÇÃO ADICIONAIS
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'agno3-nabr',
        reactants: ['AgNO3', 'NaBr'],
        products: ['AgBr', 'NaNO3'],
        equation: 'AgNO₃ + NaBr → AgBr↓ + NaNO₃',
        description: 'Precipitado amarelo-claro de brometo de prata!',
        type: 'precipitation',
        effect: 'precipitate',
        effectColor: '#fffacd',
        productColor: '#fffacd',
        exothermic: false,
    },
    {
        id: 'agno3-nai',
        reactants: ['AgNO3', 'NaI'],
        products: ['AgI', 'NaNO3'],
        equation: 'AgNO₃ + NaI → AgI↓ + NaNO₃',
        description: 'Precipitado amarelo de iodeto de prata!',
        type: 'precipitation',
        effect: 'precipitate',
        effectColor: '#ffff00',
        productColor: '#ffff00',
        exothermic: false,
    },
    {
        id: 'bacl2-na2so4',
        reactants: ['BaCl2', 'Na2SO4'],
        products: ['BaSO4', 'NaCl'],
        equation: 'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl',
        description: 'Precipitado branco de sulfato de bário!',
        type: 'precipitation',
        effect: 'precipitate',
        effectColor: '#ffffff',
        productColor: '#ffffff',
        exothermic: false,
    },
    {
        id: 'fecl3-kscn',
        reactants: ['FeCl3', 'KSCN'],
        products: ['Fe(SCN)3', 'KCl'],
        equation: 'FeCl₃ + 3KSCN → Fe(SCN)₃ + 3KCl',
        description: 'VERMELHO SANGUE! Tiocianato de ferro (teste para Fe³⁺)',
        type: 'synthesis',
        effect: 'glow',
        effectColor: '#8b0000',
        productColor: '#8b0000',
        exothermic: false,
    },
    {
        id: 'cuso4-naoh-hot',
        reactants: ['CuSO4', 'NaOH'],
        products: ['CuO', 'Na2SO4', 'H2O'],
        equation: 'CuSO₄ + 2NaOH → Cu(OH)₂↓ → CuO + H₂O (aquecimento)',
        description: 'Precipitado azul → preto com aquecimento',
        type: 'precipitation',
        effect: 'precipitate',
        effectColor: '#1e90ff',
        productColor: '#1e90ff',
        exothermic: false,
    },

    // ═══════════════════════════════════════════════════════════════════
    // DECOMPOSIÇÕES TÉRMICAS
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'h2o2-mno2',
        reactants: ['H2O2', 'MnO2'],
        products: ['H2O', 'O2'],
        equation: '2H₂O₂ → 2H₂O + O₂↑ (catalisador MnO₂)',
        description: 'Decomposição catalítica: Oxigênio liberado!',
        type: 'decomposition',
        effect: 'bubbles',
        effectColor: '#ffffff',
        productColor: '#e0ffff',
        exothermic: true,
    },
    {
        id: 'nahco3-heat',
        reactants: ['NaHCO3', 'NaHCO3'],
        products: ['Na2CO3', 'CO2', 'H2O'],
        equation: '2NaHCO₃ → Na₂CO₃ + CO₂↑ + H₂O (aquecimento)',
        description: 'Decomposição térmica do bicarbonato de sódio',
        type: 'decomposition',
        effect: 'bubbles',
        effectColor: '#e8e8e8',
        productColor: '#ffffff',
        exothermic: false,
        requiredTemp: { min: 80, max: 5000 },
    },
    {
        id: 'caco3-heat',
        reactants: ['CaCite', 'heat'],
        products: ['CaO', 'CO2'],
        equation: 'CaCO₃ → CaO + CO₂↑ (calcinação)',
        description: 'Calcinação: Produção de cal viva!',
        type: 'decomposition',
        effect: 'smoke',
        effectColor: '#e8e8e8',
        productColor: '#fffaf0',
        exothermic: false,
        requiredTemp: { min: 800, max: 5000 },
    },

    // ═══════════════════════════════════════════════════════════════════
    // COMPLEXAÇÃO E REAÇÕES COLORIDAS
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'cuso4-nh4oh',
        reactants: ['CuSO4', 'NH4OH'],
        products: ['Cu(NH3)4SO4', 'H2O'],
        equation: 'CuSO₄ + 4NH₃ → [Cu(NH₃)₄]SO₄',
        description: 'AZUL INTENSO! Formação do íon tetraminocobre(II)',
        type: 'synthesis',
        effect: 'glow',
        effectColor: '#0000cd',
        productColor: '#0000cd',
        exothermic: false,
    },
    {
        id: 'fecl3-tannin',
        reactants: ['FeCl3', 'C76H52O46'],
        products: ['FeC76H52O46Cl3'],
        equation: 'FeCl₃ + Tanino → Complexo ferro-tanino (preto)',
        description: 'Teste para taninos: Cor preta intensa!',
        type: 'synthesis',
        effect: 'glow',
        effectColor: '#000000',
        productColor: '#1a1a1a',
        exothermic: false,
    },
    {
        id: 'ki-cl2',
        reactants: ['KI', 'Cl2'],
        products: ['KCl', 'I2'],
        equation: '2KI + Cl₂ → 2KCl + I₂',
        description: 'Liberação de iodo (cor roxa/marrom)',
        type: 'displacement',
        effect: 'glow',
        effectColor: '#4b0082',
        productColor: '#4b0082',
        exothermic: true,
    },
    {
        id: 'i2-starch',
        reactants: ['I2', 'C6H10O5'],
        products: ['I2-starch'],
        equation: 'I₂ + Amido → Complexo Iodo-Amido (azul)',
        description: 'Teste para amido: Cor azul escura!',
        type: 'synthesis',
        effect: 'glow',
        effectColor: '#000080',
        productColor: '#000080',
        exothermic: false,
    },

    // ═══════════════════════════════════════════════════════════════════
    // NEUTRALIZAÇÕES ADICIONAIS
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'h2so4-koh',
        reactants: ['H2SO4', 'KOH'],
        products: ['K2SO4', 'H2O'],
        equation: 'H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O',
        description: 'Neutralização: Sulfato de potássio formado',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#ffff00',
        productColor: '#f5f5f5',
        exothermic: true,
    },
    {
        id: 'hcl-nh4oh',
        reactants: ['HCl', 'NH4OH'],
        products: ['NH4Cl', 'H2O'],
        equation: 'HCl + NH₄OH → NH₄Cl + H₂O',
        description: 'Neutralização: Formação de cloreto de amônio',
        type: 'neutralization',
        effect: 'smoke',
        effectColor: '#ffffff',
        productColor: '#f5f5f5',
        exothermic: true,
    },
    {
        id: 'ch3cooh-naoh',
        reactants: ['CH3COOH', 'NaOH'],
        products: ['CH3COONa', 'H2O'],
        equation: 'CH₃COOH + NaOH → CH₃COONa + H₂O',
        description: 'Neutralização: Acetato de sódio formado',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#fffacd',
        productColor: '#f5f5f5',
        exothermic: true,
    },
    {
        id: 'h3po4-naoh',
        reactants: ['H3PO4', 'NaOH'],
        products: ['Na3PO4', 'H2O'],
        equation: 'H₃PO₄ + 3NaOH → Na₃PO₄ + 3H₂O',
        description: 'Neutralização: Fosfato de sódio formado',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#ffff00',
        productColor: '#f5f5f5',
        exothermic: true,
    },

    // ═══════════════════════════════════════════════════════════════════
    // COMBUSTÕES
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'c2h5oh-o2',
        reactants: ['C2H5OH', 'O2'],
        products: ['CO2', 'H2O'],
        equation: 'C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O',
        description: 'Combustão do etanol: Chama azulada!',
        type: 'combustion',
        effect: 'fire',
        effectColor: '#4169e1',
        productColor: '#e8e8e8',
        exothermic: true,
        requiredTemp: { min: 350, max: 5000 },
    },
    {
        id: 'ch3oh-o2',
        reactants: ['CH3OH', 'O2'],
        products: ['CO2', 'H2O'],
        equation: '2CH₃OH + 3O₂ → 2CO₂ + 4H₂O',
        description: 'Combustão do metanol: Chama quase invisível!',
        type: 'combustion',
        effect: 'fire',
        effectColor: '#87ceeb',
        productColor: '#e8e8e8',
        exothermic: true,
        requiredTemp: { min: 380, max: 5000 },
    },
    {
        id: 'h2-o2',
        reactants: ['H2', 'O2'],
        products: ['H2O'],
        equation: '2H₂ + O₂ → 2H₂O',
        description: 'Síntese da Água! Reação exotérmica vigorosa',
        type: 'synthesis',
        effect: 'bubbles',
        effectColor: '#87ceeb',
        productColor: '#4ecdc4',
        exothermic: true,
        requiredTemp: { min: 25, max: 5000 }, // Temperatura ambiente ou maior (com catalisador imaginário)
        optimalRatio: 0.5, // 2 mols H2 : 1 mol O2
    },
    {
        id: 'ch3coch3-o2',
        reactants: ['CH3COCH3', 'O2'],
        products: ['CO2', 'H2O'],
        equation: 'CH₃COCH₃ + 4O₂ → 3CO₂ + 3H₂O',
        description: 'Combustão da acetona: Altamente inflamável!',
        type: 'combustion',
        effect: 'fire',
        effectColor: '#ff6600',
        productColor: '#e8e8e8',
        exothermic: true,
        requiredTemp: { min: 460, max: 5000 },
    },
    {
        id: 'c-o2',
        reactants: ['C', 'O2'],
        products: ['CO2'],
        equation: 'C + O₂ → CO₂',
        description: 'Combustão do Carbono: Produção de Dióxido de Carbono',
        type: 'combustion',
        effect: 'fire',
        effectColor: '#ff6600',
        productColor: '#e8e8e8',
        exothermic: true,
        requiredTemp: { min: 400, max: 5000 },
    },

    // ═══════════════════════════════════════════════════════════════════
    // INDICADORES DE pH
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'phenol-acid',
        reactants: ['phenolphthalein', 'HCl'],
        products: ['phenolphthalein-clear'],
        equation: 'Fenolftaleína + Ácido → Incolor',
        description: 'Fenolftaleína fica INCOLOR em meio ácido',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#f5f5f5',
        productColor: '#f5f5f5',
        exothermic: false,
    },
    {
        id: 'bromothymol-acid',
        reactants: ['bromothymol', 'HCl'],
        products: ['bromothymol-yellow'],
        equation: 'Azul de Bromotimol + Ácido → Amarelo',
        description: 'Bromotimol fica AMARELO em meio ácido!',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#ffff00',
        productColor: '#ffff00',
        exothermic: false,
    },
    {
        id: 'bromothymol-base',
        reactants: ['bromothymol', 'NaOH'],
        products: ['bromothymol-blue'],
        equation: 'Azul de Bromotimol + Base → Azul',
        description: 'Bromotimol fica AZUL em meio básico!',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#0000ff',
        productColor: '#0000ff',
        exothermic: false,
    },
    {
        id: 'methyl-acid',
        reactants: ['methyl_orange', 'HCl'],
        products: ['methyl_orange-red'],
        equation: 'Alaranjado de Metila + Ácido → Vermelho',
        description: 'Alaranjado de metila fica VERMELHO em ácido!',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#ff0000',
        productColor: '#ff4500',
        exothermic: false,
    },
    {
        id: 'methyl-base',
        reactants: ['methyl_orange', 'NaOH'],
        products: ['methyl_orange-yellow'],
        equation: 'Alaranjado de Metila + Base → Amarelo',
        description: 'Alaranjado de metila fica AMARELO em base!',
        type: 'neutralization',
        effect: 'glow',
        effectColor: '#ffa500',
        productColor: '#ffd700',
        exothermic: false,
    },

    // ═══════════════════════════════════════════════════════════════════
    // DESLOCAMENTOS METÁLICOS
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'fe-h2so4',
        reactants: ['Fe', 'H2SO4'],
        products: ['FeSO4', 'H2'],
        equation: 'Fe + H₂SO₄ → FeSO₄ + H₂↑',
        description: 'Ferro em ácido: Liberação de hidrogênio!',
        type: 'displacement',
        effect: 'bubbles',
        effectColor: '#e0ffff',
        productColor: '#90ee90',
        exothermic: true,
    },
    {
        id: 'al-hcl',
        reactants: ['Al', 'HCl'],
        products: ['AlCl3', 'H2'],
        equation: '2Al + 6HCl → 2AlCl₃ + 3H₂↑',
        description: 'Alumínio em ácido: Reação vigorosa!',
        type: 'displacement',
        effect: 'bubbles',
        effectColor: '#ffffff',
        productColor: '#f5f5f5',
        exothermic: true,
    },
    {
        id: 'cu-agno3',
        reactants: ['Cu', 'AgNO3'],
        products: ['Cu(NO3)2', 'Ag'],
        equation: 'Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag',
        description: 'Cobre desloca prata: Cristais de prata formados!',
        type: 'displacement',
        effect: 'precipitate',
        effectColor: '#c0c0c0',
        productColor: '#4169e1',
        exothermic: false,
    },
]

// Função para mesclar com as reações originais
export function getAllReactions(): ChemicalReaction[] {
    // Importar do ChemistryEngine seria circular, então apenas exportamos as novas
    return EXPANDED_REACTIONS
}
